### ISSUE TITLE
Slow SSL (4 lines per second or less) on Linux

### ISSUE THREAD

**Issue by j4jackj** [evilnet/nefarious2#13]
I have tried every possible configuration that I can think of, and all clients connected via SSL (including servers) are being sent connection footers noticeable more slowly than non-SSL. On your network, it's not noticeable. How do you achieve this? Oh, and the revision you told me on IRC didn't work.

**Comment by jobe1986** [comment]
Unable to replicate or even experience this issue anywhere any more. If it reoccurs, then this issue can be reopened.
