### ISSUE TITLE
Nasty bug linking to BewareIRCd

### ISSUE THREAD

**Issue by j4jackj** [evilnet/nefarious2#21]
Steps to reproduce:
* Install Nefarious on 64-bit machine
* Install BewareIRCd on another 64-bit machine
* Configure the two to link
* Tell one to link to the other
Result: segmentation fault on the Nefarious side. This bug has been tested with the latest git-clone of Nefarious2.

**Comment by jobe1986** [comment]
Neafrious is not guaranteed to be compatible with any other IRCd, and is only compatible with P10 based IRCd's in theory alone. That is when careful consideration is taken as to what features to enable/disable on BOTH sides of the link to ensure compatibility. As such I see no reason to leave this issue open however I will test at some point.
