### ISSUE TITLE
channel modes +Q make kill the ircd proccess

### ISSUE THREAD

**Issue by WildClaudio** [evilnet/nefarious2#26]
+Q Strip QUIT/PART messages */ <--  when i set this channel mode on a channel and i part the channel with a message the ircd proccess is killed SIG_SERV error !!! 
 "CHMODE_Q" = "TRUE"; <-- ircd.conf line !!!

problem solved !!!

Program received signal SIGSEGV, Segmentation fault.
HasColor (text=0x0) at ircd_string.c:756
756 for (tmp = text; (*tmp); tmp++) {
#0 HasColor (text=0x0) at ircd_string.c:756

fixed by adding

if (text != NULL) { }
the code looks like this:

int HasColor(const char* text)
{
  const char *tmp;
  if (text != NULL) {
  for (tmp = text; (*tmp); tmp++) {
    if (*tmp & 224) continue;
    switch (*tmp) {
      case COLOR_BOLD:
      case COLOR_REVERSE:
      case COLOR_UNDERLINE:
      case COLOR_ITALIC:
      case COLOR_NORMAL:
      case COLOR_COLOR:
        return 1;
      default:;
    }
  }
}
  return 0;
}

**Comment by frootv** [comment]
ALLOW_OPLEVEL_CHANGE = FALSE and you will be fine ;)

**Comment by jobe1986** [comment]
Closing as I am unable to replicate.or even work out how the explanation even lead to the crash in question.
