### ISSUE TITLE
ability to configure ciphers used.

### ISSUE THREAD

**Issue by uttra-** [evilnet/nefarious2#28]
having an option in conf files to configure the ciphers allowed when connecting over ssl.

There are currently many weak ciphers being used, android for instance will default to tls1-rc4-md5.
and many clients are unable to configure cipher being used they end up negotiating  weak, broken and insecure ciphers.

**Comment by jobe1986** [comment]
Added in revision 6fc102f46b9928ac060293a155f94c575c1e8883
