### ISSUE TITLE
/whois command not showing real USER/HOTS IP (IPV6)

### ISSUE THREAD

**Issue by WildClaudio** [evilnet/nefarious2#38]
Hello i just saw today that using whois/extemded whois on users with a real HostName wont show me the user/host real ip  in the whois reply even if i am loged as oper/admin !!
Example a whois to a user that used /sethost command "fake hostname"

[13:32:11] *** Ioana is identd@Ioana.Lost.In.Future
[13:32:11] *** Ioana is «LOST !!!»
[13:32:11] *** Ioana on server.com «Welcome !!!»
[13:32:11] *** Ioana nextirc@2a00:d880:5:26e::aaaa 2a00:d880:5:26e::aaaa Actual user@host, Actual IP

Example a whois to a user using a a hostname setup under a ipv6 ip

[13:38:13] *** Wrong is report@WRONG.WRONG.WRONG.NextIRC.gq
[13:38:13] *** Wrong is «@ Wrong @»
[13:38:13] *** Wrong on server.com «Welcome !!!»
[13:38:13] *** Wrong on status
[13:38:13] *** Wrong idle 3 s, signed on «Tue 7th Apr 2015 01:38:10»

this happens only to users who have a hostname under a ipv6 ip !!!

**Comment by jobe1986** [comment]
Actually this happens ALWAYS as long as the user does NOT have his/her host name hidden by host hiding, spoofhost blocks or a fake host. This was a decision made by the undernet developers in ircu itself and is thus intended behaviour. We presume the reasoning is that as long as the real host is visible the IP address can be determined with a DNS lookup. This behaviour is not limited to IPv6, it applies to IPv4 too. To prove this, connect as a user via IPv4, and use /mode <yournick> -x to remove host hiding completely, then /whois <yournick> and youll see the host+ip line is not shown.

The code in question is:
    if (IsHiddenHost(acptr) && (IsAnOper(sptr) || acptr == sptr))
      send_reply(sptr, RPL_WHOISACTUALLY, name, user->username,
                 user->realhost, ircd_ntoa(&cli_ip(acptr)));

Which means if the user being /whois'ed has user mode +x, and the user performing the /whois is either an IRCop or is the user who is being /whois'ed then show the realhost+ip line.

**Comment by WildClaudio** [comment]
yes you have right THANK YOU for the quick reply and explanation the truth is that the ipv4 user that i whois`ed was with +wxi modes , we should use a irc client who is able to DNS ipv6 hostnames or ask our ISP`s to implement the ipv6 protocol to be able to do this, untill then w`ll use a website or the check command to be able to see the ipv6 ip under a hostname :) topic "issue" can be close now as is solved :)

**Comment by WildClaudio** [comment]
Thank YOU Again !!!
