### ISSUE TITLE
Remove / Reduce (client) Flood limits via ircd.conf

### ISSUE THREAD

**Issue by uttra-** [evilnet/nefarious2#39]
Currently missing an option in ircd.conf to reduce and/or remove the flood limit(s) as per defined in the  IRC RFC 1459, which pretty much limits it to 1 message every two seconds after an initial burst.

Having options to define how many messages are burstable, and secondly what the delay should be after burst.  (default 2 seconds / message)

**Comment by jobe1986** [comment]
RFC1459 does not specify that said flood limits should be configurable. However the configuration options which apply to delaying messages are fakelagminimum and fakelagfactor in the class block (see the [Classes] section of example.conf). The defaults in Nefarious 2 for these 2 settings are 2 for fakelagminimum and 120 for fakelagfactor. There is currently no option to specify how many messages are burstable but according to the comments in the source doe the above defaults allow for 5 burstable messages then one message every 2 seconds.

To remove the fake lag feature for a client completely you need to define a class block with fakelagfactor set to 0 and then use either a Client block, or an Operator block to put the user into that class.

**Comment by uttra-** [comment]
sorry, I was unclear, it was more how (flood limits) are defined in the rfc:  ("* while the timer is less than ten seconds ahead of the current time, parse any present messages and penalize the client by 2 seconds for each message;" 

not that the rfc specified it should be configurable.

i remember i asked about such a while ago on the irc channel, and spoke to you about it, 
 think it was solved by commenting out the whole delay, and recompiling.  anyways, thanks for answer

**Comment by jobe1986** [comment]
That sounds like a solution I'd have suggested prior to adding the above mentioned options. But now with said options it's not necessary to edit the source code. If you just want to remove the fake lag for all clients you can simply add fakelagfactor = 0; to all class blocks.
