### ISSUE TITLE
channel mode +r / s_err 

### ISSUE THREAD

**Issue by WildClaudio** [evilnet/nefarious2#48]
when a channel is set +r *only registered nicknames/accounts* wont show the right error line as is set in s_err.c <--> calling the "ERR_NEEDREGGEDNICK"  m_join.c
/* 477 */
  { ERR_NEEDREGGEDNICK, "%s :Cannot join channel (+r): this channel requires authentication -- you can obtain an account from %s", "477" },

instead is showing this message

[19:12:20] *** [cannot] join channel- You must have a registered nick (mode +R)

**Comment by jobe1986** [comment]
Unless you modified Nefarious' source code to make it do so, the message you showed did NOT come from Nefarious as that message text does not appear in Nefarious' source code. That is unless you modified Nefarious to send that message.

I can confirm that Nefarious does send the correct message (which you quoted from the source code):
```
JOIN #jobe
:alpha.invictachat.net 477 Eboj #Jobe :Cannot join channel (+r): this channel requires authentication -- you can obtain an account from http://sourceforge.net/projects/evilnet/
```

**Comment by Gatewayy** [comment]
That's an interesting discovery! 

On 2016-05-01 01:16, Matthew Beeching wrote: 

> Unless you modified Nefarious' source code to make it do so, the message you showed did NOT come from Nefarious as that message text does not appear in Nefarious' source code. That is unless you modified Nefarious to send that message. 
> 
> I can confirm that Nefarious does send the correct message (which you quoted from the source code): 
> 
> JOIN #jobe
> :alpha.invictachat.net 477 Eboj #Jobe :Cannot join channel (+r): this channel requires authentication -- you can obtain an account from http://sourceforge.net/projects/evilnet/
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub [1]

  

Links:
------
[1]
https://github.com/evilnet/nefarious2/issues/48#issuecomment-216019007
