### ISSUE TITLE
/whox IPV6

### ISSUE THREAD

**Issue by WildClaudio** [evilnet/nefarious2#53]
it seams to be a problem with /whox command and ipv6 ips will work only if you`ll use first 4 numbers_first blocck_ and \* from a ipv6 IP
/who 2604\* x%nc
**\* #idle LG
**\* #idle Persia
**\* #idle Pamela
**\* #idle Waki
**\* #idle Wanda
 now trying to search one client using /whox wont work

/who 2604:880:c:bb:4:7ec0:4:48 x%nc
End of WHO matching 2604:880:c:bb:4:7ec0:4:48 - 0 user(s) found <--- this beeing Wanda nickname from above exemple 

same result using /who 2604:880:\*  x%nc or   /who 2604:\*  x%nc

to mention: ipv4 works great

/who 1.2.4.\* x%nc
**\* #channel Allexa
**\* End of WHO matching 1.2.4.\* - 1 user(s) found

Thank You In Advance !!

**Comment by jobe1986** [comment]
Try "/who 2604* xi%nc" instead

As documented in doc/readme.who the "i" flag means the mask provided is to be matched against the users' real IP address. Without the "i" flag with only the "x" flag, the mask supplied is matched only against nick, channel and displayed host name (cloaked, vhost, rDNS etc..) as apposed to real host name or IP address.
