### ISSUE TITLE
spoofhost block..

### ISSUE THREAD

**Issue by SebLemery** [evilnet/nefarious2#59]
Hi, so im having issues with my config. precisely the spoofhost section. 
this is the code in there. 
```
Spoofhost "network@jedi.knight" {
  host = "seb@li111-111.members.linode.com";
  autoapply = yes;
  ismask = no;
  matchusername = no;
};

Spoofhost "network@jedi.master" {
  host = "Seb@modemcable000.000-000-000.mc.videotron.ca";
  autoapply = yes;
  ismask = no;
  matchusername = no;
};
```

So the first one (linode host) is mine and works as intended (i even added color codes and it works) i am an ADMIN in the config (Server Admin). the second one is my eggdrop, he is not an oper just a USER. I also tried with various hostnames, just the ips. with other users, on various installations and it's not spoofing the second host.. am i doing something wrong? Should they all be in one single block? or one host per page. im so confused.

**Comment by jobe1986** [comment]
Try setting matchusername to yes. If set to no, the portion of the host mask before the match ONLY matches against successful identd replies.

**Comment by SebLemery** [comment]
> Try setting matchusername to yes

Well damit, this was the issue. Thanks. :)
