### ISSUE TITLE
(Too many connections from your host) after gline removal

### ISSUE THREAD

**Issue by ZioNeL** [evilnet/nefarious2#63]
Hello. We noticed that after removing a gline the person who was glined receives (Too many connections from your host) even if no one from that host or ip is connected on server.
This issue appear only for glines that are removed before initial expiration time. For example: I gline a user for 2 hours but after 30 minute a remove the gline. Until the original expiration time don`t pass the (Too many connections from your host) issue remains.

**Comment by jobe1986** [comment]
By any chance is the gline mask in question a *@<ip> mask?

**Comment by ZioNeL** [comment]
yes, the gline is set as *@ip or *@host

**Comment by jobe1986** [comment]
Can you try the latest commit and see if that resolves the issue please?

**Comment by ZioNeL** [comment]
With the latest fix, the issue is fixed.
Thank you.
